import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/StoreProvider";
import { getSeoConfig } from "@/lib/server/seoConfig";
import { fetchGlobalConfig } from "@/lib/api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const DEFAULT_META = {
  title: "My Next Project",
  description: "Generated by Next.js",
};

export async function generateMetadata(): Promise<Metadata> {
  const seo = await getSeoConfig();
  let favicon: string | undefined;

  try {
    const globalConfig = await fetchGlobalConfig();
    if (globalConfig.favicon) {
      favicon = `${process.env.NEXT_PUBLIC_API_URL}/${globalConfig.favicon}`;
    }
  } catch (error) {
    console.error("Failed to fetch global config for favicon:", error);
  }

  const metadata: Metadata = {
    title: seo?.metaTitle || DEFAULT_META.title,
    description: seo?.metaDescription || DEFAULT_META.description,
    keywords: seo?.metaKeywords,
  };

  if (favicon) {
    metadata.icons = {
      icon: favicon,
    };
  }

  if (seo?.googleAnalyticCode) {
    metadata.other = {
      "google-analytics": "enabled",
    };
  }

  return metadata;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const seoConfig = await getSeoConfig();

  return (
    <html lang="en">
      <head>
        {seoConfig?.metaKeywords && (
          <meta name="keywords" content={seoConfig.metaKeywords} />
        )}
        {seoConfig?.googleAnalyticCode && (
          <script
            dangerouslySetInnerHTML={{
              __html: `
                try {
                  ${seoConfig.googleAnalyticCode}
                } catch (e) {
                  console.warn('Analytics script error:', e);
                }
              `,
            }}
          />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
