import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/StoreProvider";
import { getSeoConfig } from "@/lib/server/seoConfig";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const DEFAULT_META = {
  title: "My Next Project",
  description: "Generated by Next.js",
};

export async function generateMetadata(): Promise<Metadata> {
  const seo = await getSeoConfig();

  return {
    title: seo?.metaTitle || DEFAULT_META.title,
    description: seo?.metaDescription || DEFAULT_META.description,
    keywords: seo?.metaKeywords,
    other: seo?.googleAnalyticCode
      ? {
          "google-analytics": "enabled",
        }
      : undefined,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const seoConfig = await getSeoConfig();

  return (
    <html lang="en">
      <head>
        {seoConfig?.metaKeywords && (
          <meta name="keywords" content={seoConfig.metaKeywords} />
        )}
        {seoConfig?.googleAnalyticCode && (
          <script
            dangerouslySetInnerHTML={{
              __html: seoConfig.googleAnalyticCode,
            }}
          />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
