"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _app_shell from './app-shell.bones.json'

configureBoneyard({"color":"#e5e5e5","darkColor":"#2a2a2a","animate":"shimmer","shimmerColor":"#f0f0f0","darkShimmerColor":"#333333","speed":"2s","shimmerAngle":110})

registerBones({
  "app-shell": _app_shell,
})
